name: "Build and Check"
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-check:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    name: "Nix build and check (${{ matrix.os }})"
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: "Install Nix ❄️"
      uses: cachix/install-nix-action@v25
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}

    - name: "Install Cachix ❄️"
      uses: cachix/cachix-action@v13
      with:
        name: meck
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'

    - name: Build full cfg
      run: nix -L build .#

    - name: Build small cfg
      run: nix -L build .#small

    - name: Flake check
      run: nix -L flake check

  automerge:
    if: contains(github.event.pull_request.labels.*.name, 'automerge')
    needs: [build-check]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - run: gh pr merge --rebase --auto
    env:
      GH_TOKEN: ${{ secrets.GH_REPO_PAT }}
