name: "Update lock file"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # dayly
jobs:
  update-lock-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v16
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v24
        with:
          pr-labels: |
            dependencies
            automated
            automerge
          pr-body: |
            Automated changes:
            ```
            {{ env.GIT_COMMIT_MESSAGE }}
            ```
          commit-msg: "chore: update flake.lock"
          token: ${{ secrets.GH_REPO_PAT }}
